version: '3'
services:
  searchcode:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - manticore
      - mysql
  mysql_seed:
    build:
      context: .
      dockerfile: ./seed.Dockerfile
    links:
      - mysql:mysqldocker
    depends_on:
      - mysql
      - manticore
  manticore:
    build:
      context: .
      dockerfile: ./manticore.Dockerfile
    ports:
      - "9306:9306"
  mysql:
    image: mysql:5.7.26
    ports:
      - "3306:3306"
    expose:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: searchcode
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
